### ISSUE TITLE
Find the length of a string

### ISSUE THREAD

**Issue by fluxsauce** [smcueto/jsObjectives#6]
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof/

After each step, log the value or question/answer.

1. Declare the value of the variable `today` as the string `I-580 is a parking lot`
2. What is the length of `today`?
3. Create a function that accepts a value and returns the length of a string or 0 if it has no length; test it with the string "the bus driver is really impatient", with the value `undefined` and the value `null`.

**Comment by fluxsauce** [comment]
Can you please move this to a `js` file? I can't execute this directly.

Also, the requirements were:

> returns the length of a string or 0 if it has no length

However, `returnLength` returns a string rather than an integer representing the length.

**Comment by fluxsauce** [comment]
Really close!

```js
projects/jsObjectives [master] » node ./js1/06.js
I-580 is a parking lot
22
34
0
0
```

This is the expected output, but you're logging from the function rather than returning the value and logging the result.

Can you refactor so `returnLength` actually returns the length? That way, the final three lines are:

```js
console.log(returnLength('the bus driver is really impatient'));
console.log(returnLength(undefined));
console.log(returnLength(null));
```

**Comment by smcueto** [comment]
Ah I see what you mean! I will do it

**Comment by fluxsauce** [comment]
Awesome!
