### ISSUE TITLE
Create arrays using the proper syntax

### ISSUE THREAD

**Issue by fluxsauce** [smcueto/jsObjectives#8]
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
- https://eslint.org/docs/rules/no-sparse-arrays

After each step, log the value or question/answer.

1. Create an empty array
2. Create an array containing the values `0`, `"one"`, `222`, `"gamma"`
3. What is a sparse array and why should it be avoided?

**Comment by fluxsauce** [comment]
Good work!

> and the true value of length is not accurate

Clarification: it is accurate, it's just more likely to contain an unexpected value if a human overlooks the extra comma.

Syntactically, it's correct, but from a maintainability and readability perspective, it's probably going to lead to a bug.

**Comment by smcueto** [comment]
>Syntactically, it's correct, but from a maintainability and readability perspective, it's probably going to lead to a bug

got it

**Comment by fluxsauce** [comment]
Great!
